Добавление описания и  библиотек в readme

diff --git a/Dockerfile.airflow b/Dockerfile.airflow
--- a/Dockerfile.airflow
+++ b/Dockerfile.airflow
@@ -1,5 +1,5 @@
-# Dockerfile для создания образа Airflow с поддержкой Spark и ClickHouse.
-# Этот Dockerfile:
+# Dockerfile.airflow для создания образа Airflow с поддержкой Spark и ClickHouse.
+# Этот Dockerfile.airflow:
 #     - Устанавливает необходимые системные утилиты (wget, default-jdk).
 #     - Устанавливает Spark.
 #     - Устанавливает Python зависимости из файла requirements.txt.
@@ -28,10 +28,19 @@ ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
 ENV SPARK_HOME=/opt/spark/spark-3.4.2-bin-hadoop3
 ENV PATH=$PATH:$JAVA_HOME/bin:$SPARK_HOME/bin
 ENV PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.9.7-src.zip
+ENV PATH="/home/airflow/.local/bin:${PATH}"
 
 # Копирование и установка Python зависимостей
 COPY requirements.txt /requirements.txt
 RUN chmod 777 /requirements.txt
+
+RUN echo '#!/bin/bash' > /usr/local/bin/debug-entrypoint && \
+    echo 'set -e' >> /usr/local/bin/debug-entrypoint && \
+    echo 'echo "PATH=$PATH"' >> /usr/local/bin/debug-entrypoint && \
+    echo 'which airflow || echo "airflow not found in PATH"' >> /usr/local/bin/debug-entrypoint && \
+    echo 'find /home/airflow/.local/bin -name airflow || echo "airflow not found in .local/bin"' >> /usr/local/bin/debug-entrypoint && \
+    echo 'exec /entrypoint "$@"' >> /usr/local/bin/debug-entrypoint && \
+    chmod +x /usr/local/bin/debug-entrypoint
 
 USER airflow
 RUN pip install --upgrade pip && \
